<?php $order = $this->getOrder(); ?>
<?php /* @var $validateHelper Dhl_OnlineRetoure_Helper_Validate */ ?>
<?php $validateHelper = Mage::helper("dhlonlineretoure/validate"); ?>

<?php
/*
 * If the block should be only visible for orders with shipments, add the check ...
 * true === $validateHelper->isOrderHasShipments($order)
 * ... to the following if-statement
 */
if (($order && $validateHelper->isModuleFrontendEnabled()
    && $validateHelper->isDeliveryNameAvailable($order)
    && Mage::getModel("dhlonlineretoure/config")->isAllowedShippingMethod($order->getShippingMethod()))
):
?>
    <?php echo $this->getReturnLinkWithHash();?>
<?php endif; ?>
