<?php $order = $this->getOrder(); ?>
<?php $validateHelper = Mage::helper("dhlonlineretoure/validate"); ?>

<?php
/*
 * If the block should be only visible for orders with shipments, add the check ...
 * true === $validateHelper->isOrderHasShipments($order)
 * ... to the following if-statement
 */
if ($order && true === $validateHelper->isDeliveryNameAvailable($order)
    && true === Mage::getModel("dhlonlineretoure/config")->isAllowedShippingMethod($order->getShippingMethod())):
?>
      <?php echo $this->getReturnLinkWithHash();?>
<?php endif; ?>