<?php /* @var $this Dhl_Account_Block_Checkout_Onepage_Parcelannouncement */?>

<?php if ($this->isParcelAnnouncementEnabled() || $this->isPreferredDeliveryDateEnabled()): ?>
<ul id="parcel_announcement_box" class="form-list" style="margin: 5px; background-color: rgb(255,204,0); padding: 5px;">
    <?php if ($this->isParcelAnnouncementEnabled()): ?>
    <li>
        <input type="checkbox" class="checkbox" title="DHL <?php echo $this->__('Package Notification') ?>" name="billing[package_notification]" value="package_notification" id="billing:package_notification" />
        <label style="float: none;" id="package_notification_label" for="billing:package_notification">DHL <?php print $this->__('Package Notification') ?></label>
    </li>
    <li>
        <span>
            <?php print $this->__('DHL keeps you informed about the planned delivery day via email.'); ?>
        </span>
    </li>
    <?php endif; ?>
    <?php if ($this->isPreferredDeliveryDateEnabled()): ?>
        <li>
            <input type="checkbox" onclick="toggleDhlAccount()" class="checkbox" title="DHL <?php print $this->__('Preferred Delivery Date'); ?>" name="billing[preferred_date]" value="0" id="billing:preferred_date">
            <label style="float: none;" id="preferred_date_label" for="billing:preferred_date">DHL <?php print $this->__('Preferred Delivery Date') ?></label>
        </li>
        <li>
            <span>
                <?php print $this->__('DHL wants to deliver your parcel but you are not at home?'); ?>
                <?php print $this->__('You can move the delivery date for your parcel by up to four working days. To do this, simply log in to your Paket.de account.'); ?>
                <?php print $this->__('In order to use this service, please provide your PostNumber with your order.'); ?>
            </span>
        </li>
        <li id="dhl_account_number" style="display: none;">
            <label id="dhl_account_label" class="required text" for="billing:dhl-account">
                <?php print $this->__('DHL account number'); ?>
                <em style="float: none; position: static; right: 0px;">*</em>
                <span style="font-size: 15px; text-decoration: none; color: #1E7EC8;"
                      title="<?php print $this->__('DHL customer account number'); ?>">
                    ?
                </span>
            </label>
            <div class="input-box" style="width: 350px;">
                <input type="text"
                       class="text required-entry"
                       title="<?php print $this->__('DHL account number'); ?>"
                       name="billing[dhlaccount]" value="" id="billing:dhl-account">
            </div>
        </li>
    <?php endif; ?>
    <li style="text-align: right;">
        <img src="<?php echo $this->getSkinUrl('images/dhl/dhl_logo.png'); ?>">
    </li>
</ul>
<?php endif; ?>

<input type="checkbox" name="shipping[resetParcelAnnouncement]" style="display: none;" id="shipping:resetParcelAnnouncement">
<script type="text/javascript">
    if ($('billing:ship_to_packstation') != null) {
        $('billing:ship_to_packstation').parentNode.parentNode.remove();
    }

    Translator.add(
        'Based on your selection, the DHL account number field will be cleared. Continue?',
        '<?php echo $this->__('Based on your selection, the DHL account number field will be cleared. Continue?'); ?>'
    );

    function toggleDhlAccount()
    {
        var display = 'none';
        if ($('billing:preferred_date').checked) {
            display = 'inline';
            $('billing:dhl-account').addClassName('required-entry');
            $('billing:dhl-account').addClassName('validate-six-to-ten-digits');
            Validation.addAllThese([
                ['validate-six-to-ten-digits', '<?php echo $this->__('Please enter 6 to 10 digits.'); ?>', function(v) {
                    return true == /^\d{6,10}$/i.test(v);
                }]]);
        } else {
            $('billing:dhl-account').removeClassName('required-entry');
            $('billing:dhl-account').removeClassName('validate-six-to-ten-digits');
            $('billing:dhl-account').value = '';
        }
        $('dhl_account_number').style.display = display;
        $('dhl_account_label').style.display = display;
    }

    function addDHLAccountToBillingForm()
    {
        var node = $('billing:dhlaccount');
        if (null != node) {
            var liWrapper = node.parentNode.parentNode;
            liWrapper.parentNode.removeChild(liWrapper);
        }
        if($('parcel_announcement_box')){
            $('billing-buttons-container').parentNode.insertBefore($('parcel_announcement_box'), $('billing-buttons-container'));
        }


    }

    addDHLAccountToBillingForm();
    $$('//[name="billing[street][]"]').invoke('addClassName', 'validate-no-parcel-pick-up-machine');
    Validation.addAllThese([
    ['validate-no-parcel-pick-up-machine', '<?php echo $this->__('No parcel pick up machines are allowed in billing address. To send to a parcel pick up machine you should enter it as shipping address.'); ?>', function(v) {
        return false == /pac?k(et)?station/i.test(v);
    }]]);

    // Magento StoreView-URL, relevant for Ajax-Calls on Helpers
    var BASE_URL = '<?php echo Mage::getUrl('', array('_forced_secure' => $this->getRequest()->isSecure())); ?>';
</script>
