<?php if ($_entity = $this->getEntity()): ?>
<style type="text/css">
.intraship {
    display: block;
    float: left;
}
/*
.intraship.label {
    color: #CC0000;
    border: 1px solid #CC0000;
    font-weight: bold;
    background-color: #FFCC00;
    padding: 5px;
    margin: 7px 0 0 0;
}
*/
.intraship.comment {
    font-weight: bold;
}
.intraship.message {
    font-weight: normal;
}
.intraship.message.failed {
    color: red;
}
intraship.message.fail
</style>
<div id="comments_block">
    <span class="field-row">
        <label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Comment Text') ?></label>
        <textarea name="comment[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
    </span>
    <?php if ($this->canSendCommentEmail()): ?>
    <div class="f-left">
        <input name="comment[is_customer_notified]" type="checkbox" id="history_notify" value="1" />
        <label class="normal" for="history_notify"><?php echo Mage::helper('sales')->__('Notify Customer') ?></label>
    </div>
    <?php endif; ?>
    <div class="f-right">
        <?php echo $this->getChildHtml('submit_button') ?>
    </div>
    <div class="clear"></div>
    <ul class="note-list">
    <?php
        foreach ($_entity->getCommentsCollection(true) as $_comment):
            $comment  = $_comment->getComment();
            $segments = explode('::', $comment);
    ?>
        <li>
            <strong><?php echo $this->helper('core')->formatDate($_comment->getCreatedAtDate(), 'medium') ?></strong>
            <?php echo $this->helper('core')->formatTime($_comment->getCreatedAtDate(), 'medium') ?><span class="separator">|</span><small><?php echo $this->helper('sales')->__('Customer') ?>
            <strong class="subdue">
            <?php if ($_comment->getIsCustomerNotified()): ?>
            <?php echo $this->helper('sales')->__('Notified') ?>
            <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
            <?php else: ?>
            <?php echo $this->helper('sales')->__('Not Notified') ?>
            <?php endif; ?>
            </strong></small>
            <br/>
            <?php if (is_array($segments) && sizeof($segments) === 4): /* var_dump($segments); */ ?>
                <span class="intraship label">
                <img src="<?php echo $this->getSkinUrl('images/dhl/icon_complete.png') ?>" alt="<?php print $segments[0]; ?>" title="<?php print $segments[0]; ?>"/>
                </span>
                <span class="intraship comment">
                <?php if ($segments[1]): ?>
                    <?php print Mage::helper('intraship')->__($segments[1]); ?>
                    <br/>
                    <?php endif; ?>
                    <span class="intraship message <?php print ((int) $segments[2] !== 0) ? 'failed' : 'success'; ?>">
                        <i><?php print Mage::helper('intraship')->__($segments[3]); ?></i>
                    </span>
                </span>
            <?php else: ?>
                <?php
                if (true === Mage::getModel('intraship/config')->isVersionRecommendedOrLarger()):
                    print $this->escapeHtml(Mage::helper('intraship')->__($comment), array('b','br','strong','i','u'));
                else:
                    print Mage::helper('intraship')->__($comment);
                endif;
                ?>
            <?php endif;?>
        </li>
    <?php endforeach; ?>
    </ul>
<script type="text/javascript">
function submitComment() {
    submitAndReloadArea($('comments_block').parentNode, '<?php echo $this->getSubmitUrl() ?>')
}

if ($('submit_comment_button')) {
    $('submit_comment_button').observe('click', submitComment);
}
</script>
</div>
<?php endif; ?>
